default: &default
  adapter: sqlite3
  pool: 5
  timeout: 5000

development:
  <<: *default
  database: db/database.db

production:
  adapter: postgresql
  encoding: unicode
  pool: 2
  host: ec2-54-235-148-19.compute-1.amazonaws.com
  database: dcs55vldcse690
  username: rhmddzqfnsizqt
  password: 2235a02522f1bba39df217276873ce6a0c6b3786a11f356a768dfd0d953c9eae