default: &default
  adapter: sqlite3
  pool: 5
  timeout: 5000

development:
  <<: *default
  database: db/database.db

production:
  adapter: postgresql
  template: template0
  encoding: UTF-8
  pool: 2
  host: <%= ENV['HOST'] %>
  database: <%= ENV['DB'] %>
  username: <%= ENV['USER'] %>
  password: <%= ENV['CRED'] %>